version: '3.8'

services:
  telegram-logger:
    build: .
    environment:
      - logger_telegram_token=${logger_telegram_token}
      - supabase_url=${supabase_url}
      - supabase_key=${supabase_key}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
 